permalink:           /:title

# Setup
title:               'Revan Manusia Tampan'
tagline:             'Revan kalo diliat jadi apa?'
description:         'Apa'
url:                 https://RevanAld.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:         Revan
  url:          GAPUNYA DOMAIN
  email:        hashshura@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
