permalink:           /:title

# Setup
title:               'Catatan Ashura'
tagline:             'Asif Hummam Rais kalau disingkat jadi apa?'
description:         'Blog pribadi Asif, seorang mahasiswa Teknik Informatika ITB, yang mungkin berisi hal-hal <i>random</i> karena pada dasarnya dunia ini dibentuk oleh entropi molekuler yang bersifat acak.'
url:                 https://hashshura.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:         Asif Hummam Rais
  url:          https://ashura.id
  email:        hashshura@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
